/* Bard Defines */
#define SONG_MINUET    0
#define SONG_MINNE     1
#define SONG_MADRIGAL  2
#define SONG_MARCH     3
#define SONG_REQUIEM   4
#define SONG_PAEON     5
#define SONG_BALLAD    6
#define SONG_LULLABY   7
#define SONG_HYMNUS    8
#define SONG_MASTERY   9
#define SONG_TRAVEL    10
#define BARD_LESSONS   11

/* Races -Xrakisis */
#define RACE_HUMAN		1
#define RACE_ELF		2
#define	RACE_GNOME		3
#define RACE_GULLYDWARF		4
#define RACE_HILLDWARF		5
#define RACE_MTDWARF		6
#define RACE_DRAGONKIND		7
#define RACE_HOBBIT		8
#define RACE_KENDER		9
#define RACE_DROW		10
#define RACE_GIANT		11
#define RACE_HALFELF		12
#define RACE_OGRE		13
#define RACE_HALFOGRE		14
#define RACE_MINOTAUR		15
#define RACE_GOBLIN		16
#define RACE_HOBGOBLIN		17 
#define RACE_DUERGARDWARF	18
#define	RACE_TROLL		19
#define RACE_HALFTROLL		20
#define RACE_ORC		21
#define RACE_HALFORC		22
#define RACE_CENTAUR		23
#define RACE_WILDELF		24
#define RACE_ARCHDEMON		25
#define RACE_ARCHANGEL		26
